name: tests

on: push


jobs:
  tests:
    name: Run Test suites
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the containers
        run: docker-compose build
      - name: Run tests
        run: docker-compose up
